### ISSUE TITLE
Can't get MASTER to compile on Linux with latest Swift April 12, 2016 snapshot

### ISSUE THREAD

**Issue by adambant** [PerfectlySoft/PerfectStarter#2]
Getting numerous errors of this type. 

/var/www/PerfectStarter/PerfectServer/Packages/PerfectLib-0.11.0/Sources/PerfectLib/PerfectServer.swift:42:45: error: missing argument label 'of:' in call
        if serverPerfectLibraries.hasPrefix("/") || serverPerfectLibraries.hasPrefix("~/") || serverPerfectLibraries.hasPrefix("./") {

Seems to be related to new Swift 3.0 changes.
https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md

It does compile with the March 23rd snapshot however.
https://swift.org/builds/development/ubuntu1510/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-ubuntu15.10.tar.gz

**Comment by kjessup** [comment]
Things are compiling now with the latest Swift May snapshot.
